spring.application.name=football-api
# Database connection properties
spring.datasource.url=jdbc:postgresql://localhost:5432/football
spring.datasource.username=postgres
spring.datasource.password=Demolisher0
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Connection pool settings
spring.datasource.initialization-mode=always
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5