spring.application.name=demo
server.port=8085

#db setting
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true

spring.datasource.url=jdbc:postgresql://localhost:5432/demo
spring.datasource.username=looppp
spring.datasource.password=Demolisher0
spring.datasource.driver-class-name=org.postgresql.driver


#SQL INIT
spring.sql.init.mode="always"
spring.sql.init.scheme=classpath:schema.sql

#Retry config
spring.datasource.hikari.connectionTimeout=20000
#Check camelcasing
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.maxLifetime=30000
spring.datasource.hikari.idleTimeout=30000